# Generated by Django 3.2.5 on 2021-07-14 11:08

from django.db import migrations


def quiz_action(apps, schema_editor):
    Quiz = apps.get_model('myapp', 'Quiz')
    Quiz.objects.create(title='Python Test1',description='models1')
    Quiz.objects.create(title='Python Test2',description='models2')

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(quiz_action, lambda x, y: None)
    ]