# Generated by Django 3.2.5 on 2021-07-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210715_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztakers',
            name='correct_answers_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
