# Generated by Django 3.2.5 on 2021-07-18 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztakers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_user_takers', to=settings.AUTH_USER_MODEL),
        ),
    ]
