# Generated by Django 3.2.5 on 2021-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_quiztakers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztakers',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
